# Generated by Django 5.1.3 on 2024-11-10 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "station",
            "0002_crew_route_station_alter_train_options_order_journey_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="station.order"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.train",
            ),
        ),
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trains",
                to="station.traintype",
            ),
        ),
    ]
