# Generated by Django 5.1.3 on 2024-11-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_ticket_order_alter_ticket_train_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("seat", "journey"), name="unique_ticket_seat_journey"
            ),
        ),
    ]
