# Generated by Django 5.1.3 on 2024-11-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0004_ticket_unique_ticket_seat_journey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
