# Generated by Django 5.1.3 on 2024-11-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0006_alter_ticket_order"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket_seat_journey",
        ),
    ]
