# Generated by Django 5.1.3 on 2024-11-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0010_alter_ticket_journey_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="journey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journey_tickets",
                to="station.journey",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="train",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="train_tickets",
                to="station.train",
            ),
        ),
    ]
